var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "              xxxx                                                              ",
   "            xx!!!!xx                                                            ",
   "             xxvxxx                                                             ",
   "               o                                                      o         ",
   "                   o o                xxxxx                      xxx            ",
   "            o                                                  xx               ",
   "  xx                                      o o                                x  ",
   "  x                     o                                 o                  x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x                  o                 xxxxxxx     xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx           xxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "        y                     x!!!!!!!!!!!x          x     x                    ",
   "                              x!!!!!!!!!!!x      y   x!!!!!x                    ",
   "                 y            x!!!!!!!!!!!x          x!!!!!x                    ",
   "                              xxxxxxxxxxxxx          xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  [" xxxxxxxxxxxxxxxx                                      x    x xxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxx           x       ",
   "                       xxxxxxxxxx    o   o                          x       x   xxxxxx               xx o         ",
   "           oo o xxxxxx               xxxxx     o o          x  xxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxx xxxxxxxxxx    ",
   "       oo o                                                                  o                     o              ",
   "     xxxxxxxxxxxxxxxx             xxxxxxxxxxxxxxxxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxxxxxx  o  ",
   "                                        !!!!!!! oooooo    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "  xxxxxx!!!!v!!!!xxxxxxxxxxxxxx  o o   xxxxxxxxxxxxxxxxxxxxxxxxxxxx o                    !!!!!xxxxxxx              ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                            xx!!!!!!xx              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         ",
   "                             xxvvvxxxxxxxxx                xxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "       !!!!!!!vvv!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxx           xxxx   xxxxxxx        xxx         xxx                  ",
   "                                                                                                                  ",
   "                              y                                                                                   ",
   "                                                                                                                  ",
   "           xxxxxxxxxxxxxxx        xxxxxxxxxx!!!!!v!!!!xxxxxxxx      o o                       oo xxxxxxxxxxxxxxx  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                      xxxxxxxxxxxxxxxx oo   o oxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxx                      ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "  y      y       y     xxxxxxxxxxxxxxxxxxx y y                             o                                      ",
   "                                                                                                                  ",
   "xxxxxx             xxxxxxxxxxxxx            xxxxxxxxxxxxx      x                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                   y                                y                                         ",
   "              xxxxx     xxxx                                                                                  ",
   "              xxxx!!v!!!xxxx                         o o                                                      ",
   "              xxxxooooooxxxx                                                                                  ",
   "                xxxxxxxxx                                                                                     ",
   "                                                                                                              ",
   "                                        o                                  o o                                ",
   "                       xxxxxxxxx                                            y       y                         ",
   "                                           y                   xxxxxxxxxxxxxxxxxxxxxxxxxx                     ",
   "                       xxxxxxxxxxxxxxxxxxxxx   y           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  ",
   "      y          y  xxxxxxxxxxxxxxxxxxxxxxxxxx      o  o    y                                                 ",
   "                                                          xxxx!!v!!xxxx                                       ",
   "                                                           xxxxoooxxxx                                        ",
   "                                                            xxxooxxx                                          ",
   "                  o                                          xxoxx                                            ",
   "            o    y    o                                       xvx                                             ",
   "        xxxxxxxxxxxxxxxxxxxxx                                                                                 ",
   "                                 xxxxxxxxx   o                            ",

   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
